name: Dotnet test
on: push
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '3.0'
      - name: Installing the tool
        run: dotnet tool install -g Microsoft.dotnet-try
